In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [3]:
df.head(1)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0

In [4]:
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales'],
    'Salary': [50000, 60000, 55000, 65000, 62000]
}

In [5]:
data

{'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'],
 'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales'],
 'Salary': [50000, 60000, 55000, 65000, 62000]}

In [8]:
df = pd.DataFrame(data ,index = ['EMP01', 'EMP02', 'EMP03', 'EMP04', 'EMP05'])

In [9]:
df

      Employee Department  Salary
EMP01    Alice         HR   50000
EMP02      Bob         IT   60000
EMP03  Charlie    Finance   55000
EMP04    David  Marketing   65000
EMP05     Emma      Sales   62000

In [10]:
df.loc['EMP03']    #LOC - location of index

Employee      Charlie
Department    Finance
Salary          55000
Name: EMP03, dtype: object

In [11]:
df.loc[['EMP01', 'EMP03']]

      Employee Department  Salary
EMP01    Alice         HR   50000
EMP03  Charlie    Finance   55000

In [12]:
df.iloc[2]   #iloc - index location

Employee      Charlie
Department    Finance
Salary          55000
Name: EMP03, dtype: object

In [13]:
df

      Employee Department  Salary
EMP01    Alice         HR   50000
EMP02      Bob         IT   60000
EMP03  Charlie    Finance   55000
EMP04    David  Marketing   65000
EMP05     Emma      Sales   62000

In [15]:
df['Bonus'] = df['Salary'] * 0.1

In [16]:
df

      Employee Department  Salary   Bonus
EMP01    Alice         HR   50000  5000.0
EMP02      Bob         IT   60000  6000.0
EMP03  Charlie    Finance   55000  5500.0
EMP04    David  Marketing   65000  6500.0
EMP05     Emma      Sales   62000  6200.0

In [19]:
new_df = df.where(df['Salary'] >= 60000)

In [20]:
new_df

      Employee Department   Salary   Bonus
EMP01      NaN        NaN      NaN     NaN
EMP02      Bob         IT  60000.0  6000.0
EMP03      NaN        NaN      NaN     NaN
EMP04    David  Marketing  65000.0  6500.0
EMP05     Emma      Sales  62000.0  6200.0

In [21]:
df['Salary_category'] = pd.cut(df['Salary'],
                               bins =[40000, 50000, 60000, 70000 ],
                               labels=['low', 'medium', 'high'])

#it use for feature engg. that mean to convert numerical feature to categorical
#bins = [0,18,32,60,100]
#labels = ['teen', 'Adult' , 'senior', 'OldAge']

In [22]:
df

      Employee Department  Salary   Bonus Salary_category
EMP01    Alice         HR   50000  5000.0             low
EMP02      Bob         IT   60000  6000.0          medium
EMP03  Charlie    Finance   55000  5500.0          medium
EMP04    David  Marketing   65000  6500.0            high
EMP05     Emma      Sales   62000  6200.0            high

In [25]:
df[['Salary', 'Bonus']].describe()

             Salary        Bonus
count      5.000000     5.000000
mean   58400.000000  5840.000000
std     5941.380311   594.138031
min    50000.000000  5000.000000
25%    55000.000000  5500.000000
50%    60000.000000  6000.000000
75%    62000.000000  6200.000000
max    65000.000000  6500.000000

In [26]:
df['Salary'].mean()

58400.0

In [27]:
df['Salary'].median()

60000.0

In [28]:
df['Salary_category'].mode()

0    medium
1      high
Name: Salary_category, dtype: category
Categories (3, object): ['low' < 'medium' < 'high']

In [29]:
#df.groupby()[]

#always use 1st paranthesis n 2nd square braces

#always use when you need more than one column calculation

#for more than 2 columns pass list in paranthesis

#in square braces output feature or numerical feature is use

In [30]:
df.groupby('Salary_category')['Salary'].mean()

<ipython-input-30-a189c8ef21e7>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Salary_category')['Salary'].mean()

Salary_category
low       50000.0
medium    57500.0
high      63500.0
Name: Salary, dtype: float64

In [31]:
df.groupby(['Salary_category', 'Department'])['Salary'].mean()

<ipython-input-31-8c549ac7bf25>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['Salary_category', 'Department'])['Salary'].mean()

Salary_category  Department
low              Finance           NaN
                 HR            50000.0
                 IT                NaN
                 Marketing         NaN
                 Sales             NaN
medium           Finance       55000.0
                 HR                NaN
                 IT            60000.0
                 Marketing         NaN
                 Sales             NaN
high             Finance           NaN
                 HR                NaN
                 IT                NaN
                 Marketing     65000.0
                 Sales         62000.0
Name: Salary, dtype: float64

In [32]:
df.groupby(['Salary_category', 'Department'])['Salary'].mean().unstack()

<ipython-input-32-fb78b3ed58e7>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['Salary_category', 'Department'])['Salary'].mean().unstack()

Department       Finance       HR       IT  Marketing    Sales
Salary_category
low                  NaN  50000.0      NaN        NaN      NaN
medium           55000.0      NaN  60000.0        NaN      NaN
high                 NaN      NaN      NaN    65000.0  62000.0

In [33]:
import seaborn as sns

In [34]:
df1 = sns.load_dataset('titanic')

In [35]:
df1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [36]:
df1.shape

(891, 15)

In [37]:
df1['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [38]:
df1['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [41]:
df1.groupby('sex')['survived'].value_counts().unstack()

survived    0    1
sex
female     81  233
male      468  109

In [44]:
df1['sex'].value_counts(normalize = True)*100

sex
male      64.758698
female    35.241302
Name: proportion, dtype: float64