## PANDAS:-- pandas is a library.
--- it is used for large amount of data.

--- It is provide the data structure and data analysis tools.

--- It is also used for data handeling and fast data manipulation.

--- flrxible data structure like Series and Dataframe.

--- Read write for various file format like excel,csv,sql,json.

--- Easy to handeling time series(time series= change the data time to time .eg:- weather,treding-chage the data second to second.)

## DATA STRUCTURE :---  A data structure is a way to organize and store data so that it can be used efficiently.

1) SERIES :- A series is a one-dimensional labelled array that can hold various data types like integers, floats, or strings.  (1D)

2) DATAFRAME :-- A DataFrame is a two-dimensional, tabular data structure (2D).

 -- -- How to create dataframe :-- eg:- data = pd.dataframe({key:values})

In [20]:
import numpy as np   ## Need to import numpy first then pandas
import pandas as pd   ## pandas is a library used for large set of data.

In [15]:
data = [10,20,30,40]

In [16]:
data

[10, 20, 30, 40]

In [17]:
pd.Series(data)  ##series is one dimension labelled array.

0    10
1    20
2    30
3    40
dtype: int64

In [21]:
## IF WANT TO CHANGE THE INDEX OF THE DATA SET.

In [22]:
index=["a","b","c","d"]

In [24]:
pd.Series(data,index=index)  ## want to change index,first add the data of the original ,put index

a    10
b    20
c    30
d    40
dtype: int64

In [58]:
## DataFrame :- it is a two minesional tabular data structure

In [27]:
data1 = {
    "name":["shweta","shruti","selu"],
    "age":[20,25,30],
    "salary":[4500,5000,70000]
}

In [28]:
data1

{'name': ['shweta', 'shruti', 'selu'],
 'age': [20, 25, 30],
 'salary': [4500, 5000, 70000]}

In [29]:
pd.DataFrame(data1)  ## we can add more than on values in the dataframe.(IN TABULAR FORMAT)

     name  age  salary
0  shweta   20    4500
1  shruti   25    5000
2    selu   30   70000

## READ :--- HOW TO READ A FILE

GO TO FILE >> SAMPLE DATA >> TAKE A TRAIN CSV DATA >> CLICK ON 3 DOTS >> COPY PATH .

In [37]:
pd.read_csv("/content/sample_data/california_housing_train.csv")  ## read a file

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [38]:
df=pd.read_csv("/content/sample_data/california_housing_train.csv")

In [39]:
df  ## we save all the data in df data structure ,nw we can durectly use the df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

## ATTRIBUTES OF PANDAS :-- WE ARE NOT USING PARANTHESIS BRACES IN ATTRIBUTES.

  1) .Index  ---- Give all the index from the data.

In [46]:
df.index

RangeIndex(start=0, stop=17000, step=1)

2) .Columns --- give all the columns from the data.

In [47]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

3) .dtypes :-- give a type of data

In [48]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

4) .info () :-- info is a method // give all info about the entire data

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

5).Values :---   Give all values in the array format.

```
# This is formatted as code
```

In [56]:
df1=pd.DataFrame({ ## we are taking another data
    "age":[22,50,60],
    "height":[94,105,40],
    "weight":[50,60,70]
})

In [59]:
df1

   age  height  weight
0   22      94      50
1   50     105      60
2   60      40      70

In [60]:
df1.values

array([[ 22,  94,  50],
       [ 50, 105,  60],
       [ 60,  40,  70]])

6) AXES :-- Give the x axes and y axes of the data.

In [65]:
df.axes

[RangeIndex(start=0, stop=17000, step=1),
 Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
        'total_bedrooms', 'population', 'households', 'median_income',
        'median_house_value'],
       dtype='object')]

7) .SIZE :-- Calculate all the elements.

In [66]:
df.size

153000

8) .SHAPE :-- CALCULATE THE ROWS AND COLUMNS.

In [67]:
df.shape

(17000, 9)

In [68]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

.HEAD :-  BY DEFAULT SHOW first 5 ROWS OF DATA AS A SAMPLE (first 5 rows)

.HEAD(1) :-- It will shows first 1 row of the data.

In [70]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [71]:
df.head(1)   ## if put one ,it will shows only 1 row as a sample.

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0

.TAIL () :--- BY DEFAULTS SHOWS LAST 5 ROWS OF DATA (last 5 rows)

.tail(1) :- It will shows last 1 row of data.

In [72]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [73]:
df.tail(2)   ## it will give last 2 rows of data.

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

.DESCRIBE () :--- Statstical summary

In [74]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000